version: '3.8'

services:

  api:

    container_name: companies-api

    build: .

    command: uvicorn api:app --host 0.0.0.0 --port 8000 --workers 2

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app
    
    restart: always